<?xml version="1.0" encoding="UTF-8"?>
<!--
 ~ Copyright 2016 CloudBees, Inc.
 ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");
 ~ you may not use this file except in compliance with the License.
 ~ You may obtain a copy of the License at
 ~
 ~     http://www.apache.org/licenses/LICENSE-2.0
 ~
 ~ Unless required by applicable law or agreed to in writing, software
 ~ distributed under the License is distributed on an "AS IS" BASIS,
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ~ See the License for the specific language governing permissions and
 ~ limitations under the License.
 -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.jenkins-ci.plugins</groupId>
    <artifactId>plugin</artifactId>
    <version>6.2221.va_045130417c9</version>
    <relativePath />
  </parent>

  <artifactId>chaos-butler</artifactId>
  <version>1.1-SNAPSHOT</version>
  <packaging>hpi</packaging>

  <name>Chaos Butler Plugin</name>
  <description>This plugin periodically wakes up and disconnects a random node to help ensure your systems resilience.</description>

  <url>https://github.com/jenkinsci/chaos-butler-plugin</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>stephenconnolly</id>
      <name>Stephen Connolly</name>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:https://github.com/jenkinsci/${project.artifactId}-plugin.git</connection>
    <developerConnection>scm:git:git@github.com:jenkinsci/${project.artifactId}-plugin.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/jenkinsci/chaos-butler-plugin</url>
  </scm>

  <properties>
    <jenkins.baseline>2.555</jenkins.baseline>
    <jenkins.version>${jenkins.baseline}.3</jenkins.version>

    <spotless.check.skip>false</spotless.check.skip>
    <ban-junit4-imports.skip>false</ban-junit4-imports.skip>
    <ban-deprecated-stapler.skip>false</ban-deprecated-stapler.skip>
    <ban-commons-lang-2.skip>false</ban-commons-lang-2.skip>
    <hpi.strictBundledArtifacts>true</hpi.strictBundledArtifacts>
    <banObsoleteDependencyOverrides.skip>false</banObsoleteDependencyOverrides.skip>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.jenkins.tools.bom</groupId>
        <artifactId>bom-${jenkins.baseline}.x</artifactId>
        <version>7002.v028a_3607ddc8</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <repositories>
    <repository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/public/</url>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/public/</url>
    </pluginRepository>
  </pluginRepositories>

</project>
